# Generated by Django 4.0.4 on 2022-06-21 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('format', models.CharField(max_length=200)),
                ('delivery', models.TextField()),
                ('every', models.IntegerField(default=2)),
                ('reccurence', models.CharField(choices=[('min', 'Minutes'), ('d', 'Day'), ('week', 'Week'), ('y', 'Year')], default='min', max_length=16)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
