# Generated by Django 4.0.4 on 2022-06-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0003_alter_post_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reccurence',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('day', 'Day'), ('week', 'Week'), ('year', 'Year')], default='min', max_length=16),
        ),
    ]
