# Generated by Django 4.0.4 on 2022-06-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0007_alter_post_format_alter_post_reccurence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=2500),
        ),
    ]
