# Generated by Django 4.0.4 on 2022-06-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0010_remove_post_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='format',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='reccurence',
            field=models.CharField(max_length=350),
        ),
    ]
