# Generated by Django 4.0.4 on 2022-06-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0012_alter_post_format_alter_post_reccurence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF File'), ('img', 'IMAGE'), ('pptx', 'Power Point FILE')], default='pdf', max_length=20),
        ),
    ]
