# Generated by Django 4.0.4 on 2022-06-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0014_remove_post_delivery_post_web_url_alter_post_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=2500),
        ),
    ]
