# Generated by Django 4.0.4 on 2022-06-29 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashbord', '0016_rename_web_url_post_delivery_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoft_account',
            name='client_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='microsoft_account',
            name='client_secret',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='microsoft_account',
            name='teneant_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='microsoft_account',
            name='microsoft_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
