# Generated by Django 4.0.4 on 2022-07-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0017_microsoft_account_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microsoft_account',
            name='microsoft_user',
        ),
        migrations.AddField(
            model_name='microsoft_account',
            name='path_of_json',
            field=models.TextField(default=''),
        ),
    ]
