# Generated by Django 4.0.4 on 2022-07-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0018_remove_microsoft_account_microsoft_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='microsoft_account',
        ),
    ]
