# Generated by Django 4.0.4 on 2022-07-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0020_microsoft_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoft_account',
            name='email_account',
            field=models.CharField(max_length=700),
        ),
    ]
