# Generated by Django 4.0.4 on 2022-07-16 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0023_post_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='at',
            field=models.TimeField(default=datetime.datetime(2022, 7, 16, 22, 49, 16, 53712), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF File'), ('ppt', 'Power Point')], default='pdf', max_length=30),
        ),
    ]
