# Generated by Django 4.0.4 on 2022-07-19 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0025_alter_post_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='at',
            field=models.TimeField(default=datetime.datetime(2022, 7, 19, 12, 56, 59, 507659), null=True),
        ),
    ]
